### ISSUE TITLE
GH actions hangs and bugs

### ISSUE THREAD

**Issue by CAPtheorem** [bobanetwork/boba_legacy#15]
1. GH actions sometimes hang at the very last step: 

<img width="747" alt="Screen Shot 2022-03-15 at 11 40 04 AM" src="https://user-images.githubusercontent.com/79423264/158448698-275066be-7d62-41f8-ae4c-b2005b5191be.png">

2. Other times, the test runs fail at the image download step.

3. Other times, integration test runs 3 or 4 fail due to timeouts - 1 and 2 tend to pass reliably.

4. Finally, in about 1/4 of GH action runs, the integration tests fail to stop correctly:

<img width="646" alt="Screen Shot 2022-03-15 at 11 41 37 AM" src="https://user-images.githubusercontent.com/79423264/158448946-0b958fdf-6cfc-4264-af21-0a5247d3491f.png">

**Comment by InoMurko** [comment]
1. is related to `tests` being added to branch protection `Status checks that are required.`. But `tests` don't exist as a github action. I've removed them 🌸 

2. _Other times, the test runs fail at the image download step._
This issue is tackled by having a retry step if the first one fails. Can you share a link to a failure of this? Maybe something isn't working right?

```
- uses: actions/download-artifact@v2
        continue-on-error: true
        id: download
        with:
          name: boba_images
          path: /tmp/bobanetwork/
      #resolving transient error:
      #An error occurred while attempting to decompress the response stream
      - name: retry artifact download on failure
        id: download_2
        if: steps.download.outcome=='failure'
        uses: actions/download-artifact@v2
        with:
          name: boba_images
          path: /tmp/bobanetwork/
```

3. We have seen this happening (@souradeep-das specifically). It hangs because boba_deployer becomes unresponsive. I'm still thinking how I could check that and restart the deployment in the background...

4. I will add retry steps!
